-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)
SELECT h.HOUR, COUNT(o.ANIMAL_ID) AS COUNT
FROM HOURS h
LEFT JOIN ANIMAL_OUTS o
    ON HOUR(o.DATETIME) = h.HOUR
GROUP BY h.HOUR;