-- 코드를 입력하세요
WITH RECURSIVE HOURS AS (
    SELECT 9 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 19
)
SELECT h.HOUR, COUNT(a.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS a
JOIN HOURS h
    ON h.HOUR = HOUR(a.DATETIME)
GROUP BY h.HOUR
ORDER BY h.HOUR